accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.user_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    path("changepass/", views.user_change_pass, name="changepass"),
    path("profile/", views.profile, name="profile"),
    path(
        "activate-user/<uidb64>/<token>",
        views.activate_user,
        name="activate",
    ),
    path("", views.accounts, name="accounts"),
    path("add", views.add_account, name="add"),
    path("delete/<int:id>", views.delete_account, name="delete"),
    path("update/<int:id>", views.update_account, name="update"),
]

product/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "product"
urlpatterns = [
    path("", views.productAdd, name="productadd"),
    path("productread/", views.ProductView, name="productread"),
    path("deleteproduct/<int:id>", views.delete_product, name="deleteproduct"),
    path("<int:id>", views.update_product, name="updateproduct"),
]

userCRUD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("product/", include("product.urls")),
    path("category/", include("category.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password/password_reset.html"
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password/password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password/password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password/password_reset_done.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from PIL import Image


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError("Users must have an email address")
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    address = models.CharField(max_length=30, blank=True)
    full_name = models.CharField(max_length=30, blank=True)
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)  # a admin user; non super-user
    admin = models.BooleanField(default=False)  # a superuser
    last_login = models.DateTimeField(blank=True, null=True, verbose_name="last login")
    USERNAME_FIELD = "email"

    # def save(self, *args, **kwargs):
    #     if self.admin != "True" and self.update_password:
    #         self.set_password(self.password)
    #     super(CustomUser, self).save(*args, **kwargs)

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

    def __str__(self):
        return self.email

    objects = UserManager()

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    def is_superuser(self):
        return self.admin


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    image = models.ImageField(default="default.png", upload_to="profile_pics/")

    def __str__(self):
        return f"{self.user.full_name} Profile"

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 200 or img.width > 200:
            output_size = (200, 200)
            img.thumbnail(output_size)
            img.save(self.image.path)

accounts/forms.py
from django import forms
from django.contrib.auth.password_validation import validate_password
from django.forms import ModelForm

from .models import CustomUser, Profile


class RegisterForm(forms.ModelForm):
    class Meta:
        model = CustomUser

        fields = ["full_name", "address", "email", "password"]

        labels = {
            "full_name": "Full Name",
            "email": "Email",
            "password": "Password",
            "address": "Address",
        }

        help_text = {
            "password": "Include numbers for better security",
        }

        error_messages = {
            "full_name": {"required": "you must enter your name"},
            "address": {"required": "You must provide a valid address"},
            "password": {"required": "You must enter your password"},
            "email": {"required": "Email required for verification"},
        }

        widgets = {
            "full_name": forms.TextInput(
                attrs={
                    "placeholder": "John Doe",
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "placeholder": "user@example.com",
                }
            ),
            "address": forms.TextInput(
                attrs={
                    "placeholder": "Kathmandu, Nepal",
                }
            ),
            "password": forms.PasswordInput(
                attrs={"placeholder": "Include numbers for better security"}
            ),
        }


class AddImageForm(ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]

        widgets = {
            "image": forms.FileInput(
                attrs={
                    "class": "form-control-file",
                }
            ),
        }

accounts/views.py
# import pdb pdb.set_trace()
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.hashers import make_password
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.shortcuts import HttpResponseRedirect, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import (DjangoUnicodeDecodeError, force_bytes,
                                   force_str, force_text)
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from .decorators import admin_access, login_excluded
from .forms import AddImageForm, RegisterForm
from .models import CustomUser, Profile
from .utlis import generate_token


# function to send an activation email
def send_activation_email(user, request):
    current_site = get_current_site(request)
    email_subject = "Complete your registration"
    email_body = render_to_string(
        "accounts/activate.html",
        {
            "user": user,
            "domain": current_site,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "token": generate_token.make_token(user),
        },
    )

    email = EmailMessage(
        subject=email_subject,
        body=email_body,
        to=[
            user.email,
        ],
    )

    email.send()


# function to register a user
@login_excluded("accounts:accounts")
def register(request):
    if request.method == "POST":
        fm = RegisterForm(request.POST)
        if fm.is_valid():
            Name = fm.cleaned_data["full_name"]
            Address = fm.cleaned_data["address"]
            Email = fm.cleaned_data["email"]
            Password = fm.cleaned_data["password"]
            if len(Name) < 4:
                raise ValidationError("Invalid Name, enter a valid name and try again.")
            if len(Address) < 4:
                raise ValidationError(
                    "Invalid Address, enter a valid address and try again."
                )
            if len(Email) < 10:
                raise ValidationError("Invalid Name, enter a valid name and try again.")
            user = CustomUser(
                email=Email,
                full_name=Name,
                address=Address,
                password=Password,
            )
            user.is_active = False
            user.set_password(Password)
            user.save()
            send_activation_email(user, request)
            messages.success(
                request,
                "User registration successful, an email has been sent to you,"
                " Verify to login.",
            )
        else:
            messages.error(request, "registration failed, try again.")
    else:
        fm = RegisterForm()
    return render(request, "accounts/register.html", {"form": fm})


# function to add user
@login_required(redirect_field_name="")
@admin_access("product:productadd")
def add_account(request):
    if not request.user.admin:
        redirect("products:products")
    if request.method == "POST":
        fm = RegisterForm(request.POST)
        if fm.is_valid():
            Name = fm.cleaned_data["full_name"]
            Address = fm.cleaned_data["address"]
            Email = fm.cleaned_data["email"]
            Password = fm.cleaned_data["password"]
            if len(Name) < 4:
                raise ValidationError("Invalid Name, enter a valid name and try again.")
            if len(Address) < 4:
                raise ValidationError(
                    "Invalid Address, enter a valid address and try again."
                )
            if len(Email) < 10:
                raise ValidationError("Invalid Name, enter a valid name and try again.")
            user = CustomUser(
                email=Email,
                full_name=Name,
                address=Address,
                password=Password,
            )
            user.set_password(Password)
            user.save()
            messages.success(request, "User details updated successfully.")
        else:
            messages.error(request, "Update Failed, try again.")
    else:
        fm = RegisterForm()
    return render(request, "accounts/manage/add.html", {"form": fm})


# function to update user details
@login_required(redirect_field_name="")
@admin_access("product:productadd")
def update_account(request, id):
    if request.method == "POST":
        data = CustomUser.objects.get(pk=id)
        pw = request.POST.copy()
        fm = RegisterForm(pw, instance=data)
        if len(request.POST["password"]) < 4:
            context = {
                "form": fm,
                "error": "Password must be greater than 3",
            }
            return render(request, "accounts/manage/update.html", context)
        pw["password"] = make_password(request.POST["password"])

        if fm.is_valid():
            fm.save()
            messages.success(request, "User details updated successfully.")
        else:
            messages.error(request, "Update Failed, try again.")
    else:
        data = CustomUser.objects.get(pk=id)
        fm = RegisterForm(instance=data)
    return render(request, "accounts/manage/update.html", {"form": fm})


# function to login
@login_excluded("accounts:accounts")
def user_login(request):
    if request.method == "POST":
        fm = AuthenticationForm(request=request, data=request.POST)
        if fm.is_valid():
            un = fm.cleaned_data["username"]
            pw = fm.cleaned_data["password"]
            user = authenticate(username=un, password=pw)
            if user is not None:
                login(request, user)
                if user.admin:  # or some other check for admin users
                    return HttpResponseRedirect("/accounts/")
                if not user.admin:  # or some other condition for normal users
                    return HttpResponseRedirect("/product/")
    else:
        fm = AuthenticationForm()
    return render(request, "accounts/login.html", {"form": fm})


# function to show the account details from the database.
@login_required(redirect_field_name="")
@admin_access("product:productadd")
def accounts(request):
    userdata = CustomUser.objects.all()
    return render(request, "accounts/manage/accounts.html", {"userdata": userdata})


# function to delete an account
@login_required(redirect_field_name="")
@admin_access("product:productadd")
def delete_account(request, id):
    if request.method == "POST":
        data = CustomUser.objects.get(pk=id)
        data.delete()
        return HttpResponseRedirect("/accounts/")


# function to log the authenticated user out.
def user_logout(request):
    logout(request)
    return HttpResponseRedirect("/accounts/login")


# function to change the password
@login_required(redirect_field_name="")
def user_change_pass(request):
    if request.method == "POST":
        fm = PasswordChangeForm(user=request.user, data=request.POST)
        if fm.is_valid():
            fm.save()
            messages.success(request, "Password changed successfully.")
            update_session_auth_hash(request, fm.user)
    else:
        fm = PasswordChangeForm(user=request.user)
    return render(request, "accounts/password/changepass.html", {"form": fm})


# function to display the details and image of the authenticated, as well as update image.
@login_required(redirect_field_name="")
def profile(request):
    if request.method == "POST":
        fm = AddImageForm(request.POST, request.FILES, instance=request.user.profile)
        if fm.is_valid():
            fm.save()
            messages.success(request, "Profile Picture Updated")
            return redirect("accounts:profile")
        else:
            messages.error(request, "Could not upload image, try again.")
    else:
        fm = AddImageForm()
    return render(request, "accounts/profile.html", {"form": fm})


# function to activate the user after the link is clicked.
def activate_user(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)

    except Exception as e:
        user = None

    if user and generate_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Email verified, login to continue.")
        return redirect(reverse("accounts:login"))
    else:
        return render(request, "accounts/activate-failed.html", {"user": user})

templates/accounts/activate.html
{% autoescape off %}
    Please use the one time link provided below to verify your account.

    http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

    You'recieving this email because {{ user.email }} signed up at our website, kindly
    ignore this email if it wasn't you.
{% endautoescape %}

templates/accounts/changepass.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% block csspart %}
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    {% endblock csspart %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Change Password</title>
    <style>
      img {
        display: block;
        max-width: 100%;
        height: auto;
      }
    </style>
  </head>
  {% load crispy_forms_tags %} {%block bodycontent%}
  <body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd">
      <a class="navbar-brand" href=""> Home </a>
    </nav>
    <div class="container mt-4 mb-4">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div
            class="card bg-white text-secondary align-items-center text-center"
          >
            <img src="{%static 'dist/img/change.png' %}" alt="forgotpass" />
            <div class="card-body">
              <h5 class="card-title .bg-primary">Change password</h5>
              <p class="card-text"></p>
              <form method="POST" novalidate>
                {% csrf_token %} {{form|crispy}}
                <input class="btn btn-primary" type="submit" value="Confirm" />
              </form>
              {% for message in messages %}
              <div class="alert alert-{{message.tags}} mt-2" role="alert">
                {{message}}
              </div>
              {% endfor %}
              <p class="card-text mt-3">Get back to profile.</p>
              <a href="{% url 'accounts:profile' %}" class="btn btn-danger"
                >Profile</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
    {%endblock bodycontent%} {%block addjquery%}
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    {% endblock addjquery %}
  </body>
</html>

templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block csspart %}
        <link
                href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
                rel="stylesheet"
        />
        <link
                rel="stylesheet"
                href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
                crossorigin="anonymous"
        />
    {% endblock csspart %}
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Login User CRUD</title>
    <style>
        img {
            display: block;
            max-width: 100%;
            height: auto;
        }
    </style>
</head>
{% load crispy_forms_tags %} {% block bodycontent %}
    <body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd">
        <a class="navbar-brand" href=""> Home </a>
    </nav>
    <div class="container mt-4 mb-4">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div
                        class="card bg-white text-secondary align-items-center text-center"
                >
                    <img src="{% static 'dist/img/login.png' %}" alt="Login"/>
                    <div class="card-body">
                        <h5 class="card-title .bg-primary">Login</h5>
                        <p class="card-text">
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} mt-2" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </p>
                        <form method="POST">
                            {% csrf_token %} {{ form|crispy }}
                            <a href="{% url 'reset_password' %}">Forgot your password?</a> </br> </br>
                            <input class="btn btn-primary" type="submit" value="Login"/>
                        </form>
                        <p class="card-text mt-3">
                            Not a registered member? Sign up first.
                        </p>
                        <a href="{% url 'accounts:register' %}" class="btn btn-danger"
                        >Register</a
                        >
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock bodycontent %} {% block addjquery %}
    <script
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"
    ></script>
{% endblock addjquery %}
</body>
</html>

templates/accounts/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block csspart %}
        <link
                href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
                rel="stylesheet"
        />
        <link
                rel="stylesheet"
                href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
                crossorigin="anonymous"
        />
    {% endblock csspart %}
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Profile</title>
    <style>
        img {
            display: block;
            max-width: 100%;
            height: auto;
        }
    </style>
</head>
{% load crispy_forms_tags %} {% block bodycontent %}
    <body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd">
        <a class="navbar-brand" href="{% url 'accounts:accounts' %}"> Home </a>
    </nav>
    <div class="container mt-5 mb-4">
        <div class="row">
            <div class="col-md-4 mx-auto">
                <div
                        class="card bg-light text-dark align-items-center text-center border border-dark rounded"
                >
                    <div class="align-items-end">
                        <a
                                href="{% url 'accounts:changepass' %}"
                                class="mt-3 btn btn btn-outline-dark align-items-end"
                        >Change my password</a
                        >
                    </div>
                    <div class="m-b-25">
                        <img
                                src="{{ user.profile.image.url }}"
                                class="img-radius"
                                alt="User-Profile-Image"
                        />
                    </div>

                    <div class="card-body">
                        <h2 class="card-title .bg-primary account-heading">
                            {{ user.full_name }}
                        </h2>
                        <p class="card-text text-secondary">{{ user.email }}</p>
                        <p class="card-text text-secondary">{{ user.address }}</p>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %} {{ form.as_p }}
                            <input
                                    class="btn btn-primary"
                                    type="submit"
                                    value="Upload Image"
                            />
                        </form>
                        <p class="card-text mt-3"></p>

                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} mt-2" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock bodycontent %} {% block addjquery %}
    <script
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"
    ></script>
{% endblock addjquery %}
</body>
</html>

templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block csspart %}
        <link
                href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
                rel="stylesheet"
        />
        <link
                rel="stylesheet"
                href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
                crossorigin="anonymous"
        />
    {% endblock csspart %}
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Register User CRUD</title>
</head>
{% load crispy_forms_tags %} {% block bodycontent %}
    <body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd">
        <a class="navbar-brand" href=""> Home </a>
    </nav>
    <div class="container mt-4 mb-4">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div
                        class="card bg-white text-secondary align-items-center text-center"
                >
                    <div class="card-body">
                        <h5 class="card-title .bg-primary">Register</h5>
                        <p class="card-text">
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} mt-2" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </p>
                        <form method="POST">
                            {% csrf_token %} {{ form|crispy }}
                            <input class="btn btn-primary" type="submit" value="Register"/>
                        </form>
                        <p class="card-text mt-3">Already a registered user? Log in.</p>
                        <a href="{% url 'accounts:login' %}" class="btn btn-danger"
                        >Login</a
                        >
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock bodycontent %} {% block addjquery %}
    <script
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"
    ></script>
{% endblock addjquery %}
</body>
</html>