category/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "category"
urlpatterns = [
    path("", views.categoryAdd, name="categoryadd"),
    path("categoryread/", views.categoryRead, name="categoryread"),
    path("deletecategory/<int:id>", views.delete_category, name="deletecategory"),
    path("<int:id>/", views.update_category, name="categoryupdate"),
]

product/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "product"
urlpatterns = [
    path("", views.productAdd, name="productadd"),
    path("productread/", views.ProductView, name="productread"),
    path("deleteproduct/<int:id>", views.delete_product, name="deleteproduct"),
    path("<int:id>", views.update_product, name="updateproduct"),
]

userCRUD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("product/", include("product.urls")),
    path("category/", include("category.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password/password_reset.html"
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password/password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password/password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password/password_reset_done.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models


# Create your models here.
class CategoryModel(models.Model):
    category_name = models.CharField(max_length=50)
    vendor = models.CharField(max_length=50)

category/forms.py
from django import forms
from django.forms import widgets

from .models import CategoryModel


class CategoryForm(forms.ModelForm):
    class Meta:
        model = CategoryModel
        fields = ["category_name", "vendor"]
        widgets = {
            "category_name": forms.TextInput(
                attrs={
                    "class": "form-group form-control w-25",
                    "Placeholder": "Enter category name",
                }
            ),
            "vendor": forms.TextInput(
                attrs={
                    "class": " form-group form-control w-25",
                    "Placeholder": "Enter vendor name",
                }
            ),
        }
        error_messages = {
            "category_name": {"required": "You must enter the category's name"},
            "vendor": {"required": "Error: vendor required"},
        }

category/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from django.shortcuts import render

from .forms import CategoryForm
from .models import CategoryModel

# Create your views here.


@login_required(redirect_field_name="")
def categoryAdd(request):
    if request.method == "POST":
        fm = CategoryForm(request.POST)
        if fm.is_valid():
            nm = fm.cleaned_data["category_name"]
            vn = fm.cleaned_data["vendor"]
            data = CategoryModel(category_name=nm, vendor=vn)
            data.save()
            messages.success(request, "New Category Added Successfully.")
            fm = CategoryForm()
        else:
            messages.error(
                request, "Category not added, fill in the details correctly."
            )

    else:
        fm = CategoryForm()

    return render(request, "category/categoryadd.html", {"form": fm})


@login_required(redirect_field_name="")
def categoryRead(request):
    data = CategoryModel.objects.all()
    return render(request, "category/categoryread.html", {"catdata": data})


@login_required(redirect_field_name="")
def delete_category(request, id):
    if request.method == "POST":
        data = CategoryModel.objects.get(pk=id)
        data.delete()
        messages.success(request, "One category deleted successfully")
    return HttpResponseRedirect("/category/categoryread")


@login_required(redirect_field_name="")
def update_category(request, id):
    if request.method == "POST":
        data = CategoryModel.objects.get(pk=id)
        fm = CategoryForm(request.POST, instance=data)
        if fm.is_valid():
            fm.save()
            messages.success(request, "Category details updated successfully.")
        else:
            messages.error(request, "Update Failed, try again.")
    else:
        data = CategoryModel.objects.get(pk=id)
        fm = CategoryForm(instance=data)
    return render(request, "category/categoryupdate.html", {"form": fm})

templates/category/categoryadd.html
{% extends "base.html" %} {% load static %}
{% block csspart %}
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}"/>
    <style>

        .errorlist {

            list-style-type: none;
            padding: 0;
            color: red;
        }
    </style>
    </head>
{% endblock csspart %}

{% block bodycontent %}
    <body class="hold-transition sidebar-mini">
    <div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Add Category</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form method="POST" novalidate>
                                {% csrf_token %}
                                <div class="card-body">
                                    {% for field in form %}
                                        {{ field }}
                                        {{ field.errors }}
                                    {% endfor %}
                                    <input type="submit" value="Add Category" class="btn btn-primary">
                            </form>
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} mt-2" role="alert">{{ message }}</div>
                            {% endfor %}

                            <!-- /.card -->
                        </div>
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock bodycontent %}

{% block addjquery %}
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- bs-custom-file-input -->
    <script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- Page specific script -->
    <script
            src="https://kit.fontawesome.com/b45233a9f7.js"
            crossorigin="anonymous"
    ></script>
    <script>
        $(function () {
            bsCustomFileInput.init();
        });
    </script>
{% endblock addjquery %}
</body>
</html>

templates/category/categoryread.html
{% extends "base.html" %} {% load static %}
<!-- Font Awesome -->

{% block csspart %}
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    </head>
{% endblock csspart %}

{% block bodycontent %}
    <body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title"><strong>Categories</strong></h4>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                {% if catdata %}
                                    <table id="example2" class="table table-bordered table-hover">
                                        <thead>
                                        <tr>
                                            <th>Category</th>
                                            <th>Vendor</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for data in catdata %}
                                            <tr>
                                                <td>{{ data.category_name }}</td>
                                                <td>{{ data.vendor }}</td>
                                                <td>
                                                    <a href="{% url 'category:categoryupdate' data.id %} "
                                                       class="btn btn-warning btn-sm">Update</a>
                                                    <form method="POST"
                                                          action="{% url 'category:deletecategory' data.id %}"
                                                          class="d-inline" action="">
                                                        {% csrf_token %}
                                                        <input type="submit" value="Delete"
                                                               class="btn btn-danger btn-sm">
                                                    </form>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                {% else %}
                                    <h4 class="text-center alert alert-warning">No Categories Found</h4>
                                {% endif %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }} mt-2" role="alert">{{ message }}</div>
                                {% endfor %}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock bodycontent %}

{% block addjquery %}
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- DataTables  & Plugins -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- Page specific script -->
    <script
            src="https://kit.fontawesome.com/b45233a9f7.js"
            crossorigin="anonymous"
    ></script>
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
{% endblock addjquery %}
</body>
</html>

templates/category/categoryupdate.html
{% extends "base.html" %} {% load static %}
<!-- Font Awesome -->

{% block csspart %}
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}"/>
    <style>

        .errorlist {
            list-style-type: none;
            padding: 0;
            color: red;
        }

    </style>
    </head>
{% endblock csspart %}


{% block bodycontent %}
    <body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Update Category</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->

                                <form method="POST" enctype="multipart/form-data" novalidate>
                                    {% csrf_token %}
                                    <div class="card-body">
                                        {% for field in form %}{{ field }}{{ field.errors }}{% endfor %}
                                        <input class="btn btn-warning" type="submit" value="Update">

                                        <a class="btn btn-info" href="{% url 'category:categoryread' %}">Back to
                                            Categories</a>

                                </form>
                                {% for message in messages %}
                                    <div class=" alert alert-{{ message.tags }} mt-2" role="alert">{{ message }}</div>
                                {% endfor %}
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock bodycontent %}

{% block addjquery %}
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- bs-custom-file-input -->
    <script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- Page specific script -->
    <script
            src="https://kit.fontawesome.com/b45233a9f7.js"
            crossorigin="anonymous"
    ></script>
    <script>
        $(function () {
            bsCustomFileInput.init();
        });
    </script>
{% endblock addjquery %}
</body>
</html>