product/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "product"
urlpatterns = [
    path("", views.productAdd, name="productadd"),
    path("productread/", views.ProductView, name="productread"),
    path("deleteproduct/<int:id>", views.delete_product, name="deleteproduct"),
    path("<int:id>", views.update_product, name="updateproduct"),
]

userCRUD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("product/", include("product.urls")),
    path("category/", include("category.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password/password_reset.html"
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password/password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password/password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password/password_reset_done.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
import datetime
import os

from django.db import models
from django.db.models.fields import CharField


def filepath(request, filename):
    old_filename = filename
    timeNow = datetime.datetime.now().strftime("%Y%m%d%H:%M:%S")
    filename = "%s%s" % (timeNow, old_filename)
    return os.path.join("uploads/", filename)


class productModel(models.Model):
    name = models.CharField(max_length=100)
    quantity = models.IntegerField()
    stock = models.IntegerField()
    price = models.IntegerField()
    image = models.ImageField(upload_to=filepath, null=True, blank=True)

product/forms.py
from django import forms

from .models import productModel


class ProductForm(forms.ModelForm):
    class Meta:
        model = productModel
        fields = ["name", "quantity", "stock", "price", "image"]
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-group form-control w-25 p-3",
                    "Placeholder": "Enter product name",
                }
            ),
            "quantity": forms.NumberInput(
                attrs={
                    "class": "form-group form-control w-25 p-3",
                    "Placeholder": "Enter quantity",
                }
            ),
            "stock": forms.NumberInput(
                attrs={
                    "class": "form-group form-control w-25 p-3",
                    "Placeholder": "Enter stock",
                }
            ),
            "price": forms.NumberInput(
                attrs={
                    "class": "form-group form-control w-25 p-3",
                    "Placeholder": "Enter price",
                }
            ),
            "image": forms.FileInput(
                attrs={
                    "class": "form-group form-control-file",
                    "Placeholder": "Upload Image",
                }
            ),
        }

        error_messages = {
            "name": {"required": "You must provide the product's name"},
            "quantity": {"required": "You must enter the quantity"},
            "stock": {"required": "You didn't specify the stock"},
            "price": {"required": "Price must be mentioned"},
            "image": {"required": "Error: user image required"},
        }

product/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import ProductForm
from .models import productModel

# Create your views here.


@login_required(redirect_field_name="")
def productAdd(request):
    if request.method == "POST":
        frm = ProductForm(request.POST)
        if frm.is_valid():
            nm = frm.cleaned_data["name"]
            qt = frm.cleaned_data["quantity"]
            st = frm.cleaned_data["stock"]
            pr = frm.cleaned_data["price"]
            img = frm.cleaned_data["image"]
            product = productModel(name=nm, quantity=qt, stock=st, price=pr, image=img)
            product.save()
            frm = ProductForm()
            messages.success(request, "Product added successfully.")

        else:
            messages.error(request, "Fill the form correctly and try again.")
    else:
        frm = ProductForm()
    return render(request, "product/productadd.html", {"form": frm})


@login_required(redirect_field_name="")
def ProductView(request):
    productdata = productModel.objects.all()
    return render(request, "product/productread.html", {"data": productdata})


@login_required(redirect_field_name="")
def delete_product(request, id):
    if request.method == "POST":
        data = productModel.objects.get(pk=id)
        data.delete()
        messages.success(request, "Product successfully deleted.")
    return HttpResponseRedirect("/product/productread")


@login_required(redirect_field_name="")
def update_product(request, id):
    if request.method == "POST":
        data = productModel.objects.get(pk=id)
        fm = ProductForm(request.POST, instance=data)
        if fm.is_valid():
            fm.save()
            messages.success(request, "User details updated successfully.")
        else:
            messages.error(request, "Update Failed, try again.")
    else:
        data = productModel.objects.get(pk=id)
        fm = ProductForm(instance=data)
    return render(request, "product/productupdate.html", {"form": fm})

templates/product/productadd.html
{%extends "base.html" %} {% load static %} 
    <!-- Font Awesome -->

    {% block csspart %}
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <!-- Theme style -->
    <link rel="stylesheet" href="{%static 'dist/css/adminlte.min.css' %}" />
    <style>
        .errorlist{
      list-style-type: none;
      padding: 0;
      color:red;
      }    
    </style>
  </head>
  {% endblock csspart %}

  {%block bodycontent%}
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container-fluid">
            <div class="row">
              <!-- left column -->
              <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                  <div class="card-header">
                    <h3 class="card-title"><strong>Add Product</strong></h3>
                  </div>
                    {% for message in messages %}
                    <div class="d-flex justify-content-center alert alert-{{message.tags}} mt-2" role="alert">Message: {{message}}</div>
                    {% endfor %}
                  <!-- /.card-header -->
                  <!-- form start -->
                  <form method="POST" enctype="multipart/form-data" novalidate>
                   {% csrf_token %}
                    <div class="card-body">
                     {% for field in form %}{{field.label_tag}}{{field}}{{field.errors}}{% endfor %}
                    <input class="btn btn-primary" type="submit" value="Add Product">
                    </div>
                  </form>
                </div>
              
                <!-- /.card -->
              </div>
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
      <!-- /.content-wrapper -->
    {%endblock bodycontent%}

    {%block addjquery%}
        <!-- jQuery -->
        <script src="{%static 'plugins/jquery/jquery.min.js' %}"></script>
        <!-- Bootstrap 4 -->
        <script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <!-- bs-custom-file-input -->
        <script src="{%static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
        <!-- AdminLTE App -->
        <script src="{%static 'dist/js/adminlte.min.js' %}"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="{%static 'dist/js/demo.js' %}"></script>
        <!-- Page specific script -->
            <script
      src="https://kit.fontawesome.com/b45233a9f7.js"
      crossorigin="anonymous"
    ></script>
        <script>
          $(function () {
            bsCustomFileInput.init();
          });
        </script>
    {% endblock addjquery %}
  </body>
</html>

templates/product/productread.html
{% extends "base.html" %} {% load static %}
<!-- Font Awesome -->

{% block csspart %}
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">

    </head>
{% endblock csspart %}

{% block bodycontent %}
    <body class="hold-transition sidebar-mini">
    <div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title"><strong>Products</strong></h4>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                {% if data %}
                                    <table id="example2" class="table table-bordered table-hover">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Quantity</th>
                                            <th>Stock</th>
                                            <th>Price</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for dt in data %}
                                            <tr>
                                                <td>{{ dt.name }}</td>
                                                <td>{{ dt.quantity }}</td>
                                                <td>{{ dt.stock }}</td>
                                                <td>{{ dt.price }}</td>
                                                <td>{{ dt.image }}</td>
                                                <td>
                                                    <a href="{% url 'product:updateproduct' dt.id %}"
                                                       class="btn btn-warning btn-sm">Update</a>
                                                    <form method="POST"
                                                          action=" {% url 'product:deleteproduct' dt.id %}"
                                                          class="d-inline" action="">
                                                        {% csrf_token %}
                                                        <input type="submit" value="Delete"
                                                               class="btn btn-danger btn-sm">
                                                    </form>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                {% else %}
                                    <h4 class="text-center alert alert-warning">No Products Found</h4>
                                {% endif %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }} mt-2" role="alert">
                                        <strong>Message: </strong>{{ message }}</div>
                                {% endfor %}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock bodycontent %}

{% block addjquery %}
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- DataTables  & Plugins -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- Page specific script -->
    <script
            src="https://kit.fontawesome.com/b45233a9f7.js"
            crossorigin="anonymous"
    ></script>
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
{% endblock addjquery %}
</body>
</html>

templates/product/productupdate.html
{% extends "base.html" %} {% load static %}
<!-- Font Awesome -->
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

{% block csspart %}
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}"/>
{% endblock csspart %}

{% block bodycontent %}
    <body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Update Product</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->

                                <form method="POST" enctype="multipart/form-data" novalidate>
                                    {% csrf_token %}
                                    <div class="card-body">
                                        {% for field in form %}{{ field.label_tag }}{{ field }}
                                            {{ field.errors }}{% endfor %}
                                        <input class="btn btn-warning" type="submit" value="Update">

                                        <a class="btn btn-info" href="{% url 'product:productread' %}">Back to
                                            Products</a>

                                </form>
                                {% for message in messages %}
                                    <div class=" alert alert-{{ message.tags }} mt-2" role="alert">
                                        <strong>Message: </strong>{{ message }}</div>
                                {% endfor %}
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock bodycontent %}

{% block addjquery %}
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- bs-custom-file-input -->
    <script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- Page specific script -->
    <script
            src="https://kit.fontawesome.com/b45233a9f7.js"
            crossorigin="anonymous"
    ></script>
    <script>
        $(function () {
            bsCustomFileInput.init();
        });
    </script>
{% endblock addjquery %}
</body>
</html>