accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.user_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    path("changepass/", views.user_change_pass, name="changepass"),
    path("profile/", views.profile, name="profile"),
    path(
        "activate-user/<uidb64>/<token>",
        views.activate_user,
        name="activate",
    ),
    path("", views.accounts, name="accounts"),
    path("add", views.add_account, name="add"),
    path("delete/<int:id>", views.delete_account, name="delete"),
    path("update/<int:id>", views.update_account, name="update"),
]

category/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "category"
urlpatterns = [
    path("", views.categoryAdd, name="categoryadd"),
    path("categoryread/", views.categoryRead, name="categoryread"),
    path("deletecategory/<int:id>", views.delete_category, name="deletecategory"),
    path("<int:id>/", views.update_category, name="categoryupdate"),
]

product/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "product"
urlpatterns = [
    path("", views.productAdd, name="productadd"),
    path("productread/", views.ProductView, name="productread"),
    path("deleteproduct/<int:id>", views.delete_product, name="deleteproduct"),
    path("<int:id>", views.update_product, name="updateproduct"),
]

userCRUD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("product/", include("product.urls")),
    path("category/", include("category.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password/password_reset.html"
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password/password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password/password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password/password_reset_done.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>User Add/Read</title>
    <!-- Google Font: Poppins -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

    {% block csspart %}
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <!-- Theme style -->
        <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}"/>
        <!-- overlayScrollbars -->
        <link
                rel="stylesheet"
                href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}"
        />
    {% endblock csspart %}
</head>

{% block bodytag %}
{% endblock bodytag %}

{% block nav %}
    <div class="wrapper d-flex justify-content-end">
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'accounts:profile' %}" class=" mr-2 btn btn-info">Profile</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'accounts:logout' %}" class="btn btn-dark">Log out</a>
                </li>
            </ul>
        </nav>
    </div>
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="index3.html" class="brand-link">
            <img
                    src="{% static 'dist/img/AdminLTELogo.png' %}"
                    alt="AdminLTE Logo"
                    class="brand-image img-circle elevation-3"
                    style="opacity: 0.8"
            />
            <span class="brand-text font-weight-light">AdminLTE 3</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img
                            src="{{ user.profile.image.url }}"
                            class="img-circle elevation-2"
                            alt="User Image"
                    />
                </div>
                <div class="info">
                    <a href="{% url 'accounts:profile' %}" class="d-block">{{ user.full_name }}</a>
                </div>
            </div>

            <!-- SidebarSearch Form -->
            <div class="form-inline">
                <div class="input-group" data-widget="sidebar-search">
                    <input
                            class="form-control form-control-sidebar"
                            type="search"
                            placeholder="Search"
                            aria-label="Search"
                    />
                    <div class="input-group-append">
                        <button class="btn btn-sidebar">
                            <i class="fas fa-search fa-fw"></i>
                        </button>
                    </div>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul
                        class="nav nav-pills nav-sidebar flex-column"
                        data-widget="treeview"
                        role="menu"
                        data-accordion="false"
                >
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-users"></i>
                            <p>
                                USER
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'accounts:add' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Add User</p>
                                </a>
                            </li>
                        </ul>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'accounts:accounts' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>View User</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon far fa-arrow-alt-circle-right"></i>
                            <p>
                                Product
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'product:productadd' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Add Product</p>
                                </a>
                            </li>
                        </ul>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'product:productread' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>View Product</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-edit"></i>
                            <p>
                                Category
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'category:categoryadd' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Add Category</p>
                                </a>
                            </li>
                        </ul>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'category:categoryread' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>View Category</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>
{% endblock nav %}

{% block bodycontent %}
{% endblock bodycontent %}

{% block redirect %}
{% endblock redirect %}
<!-- /.content-wrapper -->
<footer class="main-footer">
    <strong
    >Copyright &copy; 2014-2021
        <a href="https://aadityadulal.com">Aaditya Dulal</a>.</strong
    >
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.1.0
    </div>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

{% block addjquery %}
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge("uibutton", $.ui.button);
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>

{% endblock addjquery %}
</body>
</html>